# 🧪 Pipeline de Datos – Ingesta y Transformación

## 🎯 Objetivo
En este laboratorio desarrollarás un pipeline básico de datos que incluye:

- Ingesta de datos desde una fuente
- Limpieza de datos
- Transformación de datos
- Generación de un dataset final listo para análisis

---

## 🧠 Contexto del Caso

Una empresa de ventas necesita analizar sus transacciones, pero los datos presentan múltiples problemas:

- Datos duplicados
- Valores nulos
- Formatos inconsistentes
- Errores en los datos

Tu misión será preparar estos datos para su uso en análisis o modelos de IA.

# 📂 Paso 1: Cargar dataset
A continuación cargaremos el dataset original de transacciones de tarjetas de crédito, que contiene posibles fraudes y errores intencionales.

Antes de ejecutar, asegúrate de tener el archivo:

📄 02_fraudTest.csv

en la carpeta IA_Proyecto/data/raw/.

In [1]:
import shutil
import logging
import os

# Crear carpeta logs en la raíz del proyecto
os.makedirs("../logs", exist_ok=True)

logging.basicConfig(filename='../logs/ingest.log', level=logging.INFO)

# Rutas correctas desde notebooks/
origen = "../data/raw/02_fraudTest.csv"
destino = "../data/raw/02_fraudTest.csv"

try:
    shutil.copy(origen, destino)
    logging.info("Archivo copiado correctamente")
    print("Ingesta completada")
except Exception as e:
    logging.error(f"Error en ingesta: {e}")

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/02_fraudTest.csv")

df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

# 🔍 Paso 2: Exploración inicial
Analiza el dataset y responde:

- ¿Hay valores nulos?
- ¿Existen duplicados?
- ¿Hay datos inconsistentes?
- ¿Hay errores en tipos de datos?

Ejecuta las siguientes celdas para explorar el dataset de transacciones de tarjetas de crédito.

In [3]:
df.info()  # Información general del dataset

<class 'pandas.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             555719 non-null  int64
 1   trans_date_trans_time  555719 non-null  str
 2   cc_num                 555719 non-null  int64
 3   merchant               555719 non-null  str
 4   category               555719 non-null  str
 5   amt                    555719 non-null  float64
 6   first                  555719 non-null  str
 7   last                   555719 non-null  str
 8   gender                 555719 non-null  str
 9   street                 555719 non-null  str
 10  city                   555719 non-null  str
 11  state                  555719 non-null  str
 12  zip                    555719 non-null  int64
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  city_pop               555719 non-null  int64
 16  job                    555719 non-null  str
 17  dob                    555719 non-null  str
 18  trans_num              555719 non-null  str
 19  unix_time              555719 non-null  int64
 20  merch_lat              555719 non-null  float64
 21  merch_long             555719 non-null  float64
 22  is_fraud               555719 non-null  int64
dtypes: float64(5), int64(6), str(12)
memory usage: 97.5 MB

In [4]:
df.isnull().sum()  # Conteo de valores nulos por columna

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [5]:
df.duplicated().sum()  # Conteo de filas duplicadas

np.int64(0)

# 🧹 Paso 3: Limpieza de datos
En este paso verificaremos y corregiremos los tipos de datos clave, y buscaremos valores inconsistentes en el dataset de transacciones de tarjetas de crédito.

- Convertir columnas de fecha y monto a su tipo correcto
- Verificar que los valores sean válidos (ejemplo: montos positivos, género válido, etc.)

In [6]:
# Conversión de tipos de datos y chequeo de valores inconsistentes
import numpy as np

# Convertir columnas de fecha
df['dob'] = pd.to_datetime(df['dob'], errors='coerce')
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'], errors='coerce')

# Convertir monto a numérico
df['amt'] = pd.to_numeric(df['amt'], errors='coerce')

# Verificar montos negativos
print('Transacciones con monto negativo:', (df['amt'] < 0).sum())

# Verificar género válido
print('Valores únicos en género:', df['gender'].unique())

# Mostrar resumen de tipos de datos y primeras filas
print(df.dtypes)
df.head()

Transacciones con monto negativo: 0
Valores únicos en género: <StringArray>
['M', 'F']
Length: 2, dtype: str
Unnamed: 0                        int64
trans_date_trans_time    datetime64[us]
cc_num                            int64
merchant                            str
category                            str
amt                             float64
first                               str
last                                str
gender                              str
street                              str
city                                str
state                               str
zip                               int64
lat                             float64
long                            float64
city_pop                          int64
job                                 str
dob                      datetime64[us]
trans_num                           str
unix_time                         int64
merch_lat                       float64
merch_long                      float64
is_fraud                          int64
dtype: object

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,33.9659,-80.9355,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,40.3207,-110.4360,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,40.6729,-73.5365,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,28.5697,-80.8191,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,44.2529,-85.0170,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0

# 🔄 Paso 4: Corrección y transformación de tipos de datos
En este paso, nos aseguraremos de que las columnas clave tengan el tipo de dato correcto y crearemos nuevas variables útiles para el análisis de fraude.

- Confirmar que las fechas y montos están correctamente convertidos
- Crear variables adicionales si es necesario (por ejemplo, año de la transacción, edad del titular, etc.)

In [7]:
# Confirmar tipos y crear variables adicionales
import pandas as pd
import numpy as np

# Confirmar tipos
print(df.dtypes)

# Crear columna: año de la transacción
df['trans_year'] = df['trans_date_trans_time'].dt.year

# Crear columna: edad del titular al momento de la transacción
df['edad'] = df['trans_date_trans_time'].dt.year - df['dob'].dt.year

# Mostrar primeras filas para verificar
df[['trans_date_trans_time', 'dob', 'trans_year', 'edad']].head()

Unnamed: 0                        int64
trans_date_trans_time    datetime64[us]
cc_num                            int64
merchant                            str
category                            str
amt                             float64
first                               str
last                                str
gender                              str
street                              str
city                                str
state                               str
zip                               int64
lat                             float64
long                            float64
city_pop                          int64
job                                 str
dob                      datetime64[us]
trans_num                           str
unix_time                         int64
merch_lat                       float64
merch_long                      float64
is_fraud                          int64
dtype: object

  trans_date_trans_time        dob  trans_year  edad
0   2020-06-21 12:14:25 1968-03-19        2020    52
1   2020-06-21 12:14:33 1990-01-17        2020    30
2   2020-06-21 12:14:53 1970-10-21        2020    50
3   2020-06-21 12:15:15 1987-07-25        2020    33
4   2020-06-21 12:15:17 1955-07-06        2020    65

# ⚙️ Paso 5: Transformación de datos
En este paso, puedes crear variables adicionales que sean relevantes para el análisis de fraude, por ejemplo:
- Diferencia de ubicación entre el titular y el comercio (distancia geográfica)
- Variables categóricas a numéricas (one-hot encoding, si es necesario para modelos)
- Otras transformaciones que faciliten el análisis o modelado

In [8]:

df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,trans_year,edad
0,0,2020-06-21 12:14:25,2291163933867244,fraud_Kirlin and Sons,personal_care,2.86,Jeff,Elliott,M,351 Darlene Green,...,333497,Mechanical engineer,1968-03-19,2da90c7d74bd46a0caf3777415b3ebd3,1371816865,33.986391,-81.200714,0,2020,52
1,1,2020-06-21 12:14:33,3573030041201292,fraud_Sporer-Keebler,personal_care,29.84,Joanne,Williams,F,3638 Marsh Union,...,302,"Sales professional, IT",1990-01-17,324cc204407e99f51b0d6ca0055005e7,1371816873,39.450498,-109.960431,0,2020,30
2,2,2020-06-21 12:14:53,3598215285024754,"fraud_Swaniawski, Nitzsche and Welch",health_fitness,41.28,Ashley,Lopez,F,9333 Valentine Point,...,34496,"Librarian, public",1970-10-21,c81755dbbbea9d5c77f094348a7579be,1371816893,40.495810,-74.196111,0,2020,50
3,3,2020-06-21 12:15:15,3591919803438423,fraud_Haley Group,misc_pos,60.05,Brian,Williams,M,32941 Krystal Mill Apt. 552,...,54767,Set designer,1987-07-25,2159175b9efe66dc301f149d3d5abf8c,1371816915,28.812398,-80.883061,0,2020,33
4,4,2020-06-21 12:15:17,3526826139003047,fraud_Johnston-Casper,travel,3.19,Nathan,Massey,M,5783 Evan Roads Apt. 465,...,1126,Furniture designer,1955-07-06,57ff021bd3f328f8738bb535c302a31b,1371816917,44.959148,-85.884734,0,2020,65

# 💾 Paso 6: Guardar dataset limpio

El dataset final será almacenado para su uso posterior.

In [11]:
# Guardar el dataset limpio para su uso posterior
df.to_csv("../data/processed/fraude_clean.csv", index=False)
print("Dataset limpio guardado correctamente en ../data/processed/fraude_clean.csv")

Dataset limpio guardado correctamente en ../data/processed/fraude_clean.csv

# 📊 Paso 7: Reflexión final

Responde las siguientes preguntas:

1. ¿Qué problemas tenía el dataset original?
2. ¿Qué decisiones tomaste para limpiar los datos?
3. ¿Qué impacto tendría NO limpiar los datos?
4. ¿Qué otras transformaciones podrías aplicar?

---

## 🚀 Conclusión

Has construido un pipeline básico de datos:

✔ Ingesta  
✔ Limpieza  
✔ Transformación  
✔ Exportación  

Este proceso es fundamental en cualquier proyecto de análisis de datos o inteligencia artificial.